version: '3.6'
services:
  app:
    build: ./
    working_dir: /app
    volumes:
      - ../:/app
      - ../.devcontainer/.bashrc:/root/.bashrc
      - ~/.ssh:/root/.ssh #sync my own local-setting
      - ~/.aws/credentials:/root/.aws/credentials
      - ~/.gitconfig:/root/.gitconfig #sync my own local-setting
      - ~/.gitignore_global:/root/.gitignore_global
      - ~/.vimrc:/root/.vimrc ##sync my own local-setting
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .env # https://code.visualstudio.com/docs/remote/containers-advanced
    tty: true
